extensions:
  health_check:
    endpoint: "0.0.0.0:13133"

receivers:
  bes:
    endpoint: "0.0.0.0:8082"

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128
  batch:
    send_batch_size: 8192
    send_batch_max_size: 8192
    timeout: 200ms

exporters:
  otlp/datadog:
    endpoint: "localhost:4317"
    tls:
      insecure: true # Only acceptable for same-host communication (e.g. sidecar Datadog Agent).
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 5000
  debug:
    verbosity: basic

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: info
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: "0.0.0.0"
                port: 8888
  pipelines:
    traces:
      receivers: [bes]
      processors: [memory_limiter, batch]
      exporters: [otlp/datadog, debug]
    logs:
      receivers: [bes]
      processors: [memory_limiter, batch]
      exporters: [debug]
