extensions:
  health_check:
    endpoint: "localhost:13133"

receivers:
  bes:
    endpoint: "localhost:8082"

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128
  batch:
    send_batch_size: 8192
    timeout: 200ms

exporters:
  # Replace with your own exporter (otlp_grpc, datadog, jaeger, etc.)
  debug:
    verbosity: detailed

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: info
  pipelines:
    traces:
      receivers: [bes]
      processors: [memory_limiter, batch]
      exporters: [debug]
    logs:
      receivers: [bes]
      processors: [memory_limiter, batch]
      exporters: [debug]
