// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("bes")
	ScopeName = "github.com/chagui/besreceiver/receiver/besreceiver"
)

const (
	TracesStability = component.StabilityLevelAlpha
	LogsStability   = component.StabilityLevelAlpha
)
