apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    uid: tempo
    jsonData:
      # Enables the "Node graph" and "Service graph" panels in the Tempo UI.
      nodeGraph:
        enabled: true
      search:
        hide: false
